#!/bin/bash

# Run wi-fi connect which will either:
#  - start AP if no existing connections
#  - try to connect to previous networks
wifi-connect --clear=false

# See if networkmanager has a connection
# Returns 0 if connected, 1 if not connected
nm-online --timeout 10

not_connected=$?

if [ $not_connected -eq 1 ]; then
  echo Not connected

  # Start green LED in heartbeat blinking whilst in AP mode
  existing_act_led_trigger=`cat /sys/devices/platform/leds/leds/led0/trigger | perl -pe 's/.*\[(.*)\].*/$1/'`
  echo timer > /sys/devices/platform/leds/leds/led0/trigger
  echo 2000 > /sys/devices/platform/leds/leds/led0/delay_on
  echo 1500 > /sys/devices/platform/leds/leds/led0/delay_off

  wifi-connect --clear=true

  echo $existing_act_led_trigger > /sys/devices/platform/leds/leds/led0/trigger

  # Now see if we're connected
  # systemd will run this script again if not
  nm-online --timeout 10
else
  echo Connected
fi
